// Building and product catalogue. Data only.
import type { BuildingConfig } from "../core/types.ts";
// prereq: null, or { building, product? } that must be unlocked before this building can be built.

export const BUILDING_CONFIG = {
	lumber_yard: {
		label: "Lumber Yard",
		desc: "Fells trees and works raw logs into precision wood components.",
		buildCost: 0,
		slotCostExponent: 1.25,
		prereq: null,
		products: {
			logs: {
				outputKey: "logs",
				outputAmt: 2,
				inputs: {},
				baseCycleMs: 2500,
				unlockCost: 0,
				baseSlotCost: 75,
				prereqProduct: null,
				startsUnlocked: true,
			},
			timber: {
				outputKey: "timber",
				outputAmt: 1,
				inputs: { logs: 2 },
				baseCycleMs: 4000,
				unlockCost: 150,
				baseSlotCost: 175,
				prereqProduct: "logs",
			},
			dowels: {
				outputKey: "dowels",
				outputAmt: 1,
				inputs: { timber: 1 },
				baseCycleMs: 6000,
				unlockCost: 750,
				baseSlotCost: 300,
				prereqProduct: "timber",
			},
			handles: {
				outputKey: "handles",
				outputAmt: 1,
				inputs: { timber: 1 },
				baseCycleMs: 8000,
				unlockCost: 1000,
				baseSlotCost: 600,
				prereqProduct: "timber",
			},
			shafts: {
				outputKey: "shafts",
				outputAmt: 1,
				inputs: { handles: 1, dowels: 1 },
				baseCycleMs: 15000,
				unlockCost: 1800,
				baseSlotCost: 1000,
				prereqProduct: "handles",
			},
		},
	},
	sawmill: {
		label: "Sawmill",
		desc: "Cuts raw logs into structural lumber for construction and trade.",
		buildCost: 25000,
		slotCostExponent: 1.35,
		prereq: { building: "lumber_yard" },
		products: {
			planks: {
				outputKey: "planks",
				outputAmt: 1,
				inputs: { logs: 1 },
				baseCycleMs: 5000,
				unlockCost: 0,
				baseSlotCost: 150,
				prereqProduct: null,
				startsUnlocked: true,
			},
			boards: {
				outputKey: "boards",
				outputAmt: 1,
				inputs: { logs: 2 },
				baseCycleMs: 10000,
				unlockCost: 500,
				baseSlotCost: 350,
				prereqProduct: "planks",
			},
			beams: {
				outputKey: "beams",
				outputAmt: 1,
				inputs: { logs: 2 },
				baseCycleMs: 12000,
				unlockCost: 1200,
				baseSlotCost: 700,
				prereqProduct: "boards",
			},
		},
	},
	workshop: {
		label: "Workshop",
		desc: "Combines lumber and precision parts into finished goods for the empire.",
		buildCost: 500000,
		slotCostExponent: 1.25,
		prereq: { building: "sawmill", product: "boards" },
		products: {
			crates: {
				outputKey: "crates",
				outputAmt: 1,
				inputs: { planks: 2, dowels: 2 },
				baseCycleMs: 20000,
				unlockCost: 0,
				baseSlotCost: 1200,
				prereqProduct: null,
				startsUnlocked: true,
			},
			furniture: {
				outputKey: "furniture",
				outputAmt: 1,
				inputs: { boards: 2, handles: 2 },
				baseCycleMs: 32000,
				unlockCost: 2000,
				baseSlotCost: 2000,
				prereqProduct: "crates",
			},
			coaches: {
				outputKey: "coaches",
				outputAmt: 1,
				inputs: { beams: 2, shafts: 2 },
				baseCycleMs: 50000,
				unlockCost: 4500,
				baseSlotCost: 3500,
				prereqProduct: "furniture",
			},
			manors: {
				outputKey: "manors",
				outputAmt: 1,
				inputs: { beams: 2, boards: 2, shafts: 2 },
				baseCycleMs: 72000,
				unlockCost: 6000,
				baseSlotCost: 5500,
				prereqProduct: "coaches",
			},
		},
	},
	forge: {
		label: "Forge",
		desc: "Smelts raw iron ore into bars and precision metalwork.",
		buildCost: 10000000,
		slotCostExponent: 1.30,
		prereq: { building: "workshop" },
		products: {
			iron_ore: {
				outputKey: "iron_ore",
				outputAmt: 1,
				inputs: {},
				baseCycleMs: 4000,
				unlockCost: 0,
				baseSlotCost: 200,
				prereqProduct: null,
				startsUnlocked: true,
			},
			iron_bars: {
				outputKey: "iron_bars",
				outputAmt: 3,
				inputs: { iron_ore: 2 },
				baseCycleMs: 9000,
				unlockCost: 500,
				baseSlotCost: 600,
				prereqProduct: "iron_ore",
			},
			nails: {
				outputKey: "nails",
				outputAmt: 1,
				inputs: { iron_bars: 1 },
				baseCycleMs: 8000,
				unlockCost: 1500,
				baseSlotCost: 1200,
				prereqProduct: "iron_bars",
			},
			iron_fittings: {
				outputKey: "iron_fittings",
				outputAmt: 1,
				inputs: { iron_bars: 2 },
				baseCycleMs: 8000,
				unlockCost: 4000,
				baseSlotCost: 2500,
				prereqProduct: "nails",
			},
		},
	},
	foundry: {
		label: "Foundry",
		desc: "Casts complex mechanisms and precision components from refined iron.",
		buildCost: 250000000,
		slotCostExponent: 1.35,
		prereq: { building: "forge", product: "iron_fittings" },
		products: {
			gears: {
				outputKey: "gears",
				outputAmt: 1,
				inputs: { iron_bars: 1, dowels: 1 },
				baseCycleMs: 30000,
				unlockCost: 0,
				baseSlotCost: 3500,
				prereqProduct: null,
				startsUnlocked: true,
			},
			springs: {
				outputKey: "springs",
				outputAmt: 1,
				inputs: { iron_fittings: 2 },
				baseCycleMs: 20000,
				unlockCost: 8000,
				baseSlotCost: 5000,
				prereqProduct: "gears",
			},
			mechanisms: {
				outputKey: "mechanisms",
				outputAmt: 1,
				inputs: { gears: 1, springs: 1 },
				baseCycleMs: 22000,
				unlockCost: 15000,
				baseSlotCost: 8000,
				prereqProduct: "springs",
			},
			clockwork: {
				outputKey: "clockwork",
				outputAmt: 1,
				inputs: { mechanisms: 1, iron_fittings: 1 },
				baseCycleMs: 90000,
				unlockCost: 25000,
				baseSlotCost: 12000,
				prereqProduct: "mechanisms",
			},
		},
	},
	armoury: {
		label: "Armoury",
		desc: "Forges weapons of war from iron, timber, and precision components.",
		buildCost: 5000000000,
		slotCostExponent: 1.30,
		prereq: { building: "foundry", product: "mechanisms" },
		products: {
			blades: {
				outputKey: "blades",
				outputAmt: 1,
				inputs: { iron_bars: 2, timber: 1 },
				baseCycleMs: 20000,
				unlockCost: 0,
				baseSlotCost: 6000,
				prereqProduct: null,
				startsUnlocked: true,
			},
			crossbows: {
				outputKey: "crossbows",
				outputAmt: 1,
				inputs: { boards: 1, shafts: 1, iron_fittings: 1 },
				baseCycleMs: 35000,
				unlockCost: 20000,
				baseSlotCost: 10000,
				prereqProduct: "blades",
			},
			cannons: {
				outputKey: "cannons",
				outputAmt: 1,
				inputs: { beams: 2, iron_bars: 2, mechanisms: 1 },
				baseCycleMs: 90000,
				unlockCost: 50000,
				baseSlotCost: 18000,
				prereqProduct: "crossbows",
			},
			artillery: {
				outputKey: "artillery",
				outputAmt: 1,
				inputs: { beams: 3, mechanisms: 2, clockwork: 1 },
				baseCycleMs: 130000,
				unlockCost: 100000,
				baseSlotCost: 30000,
				prereqProduct: "cannons",
			},
		},
	},
	shipyard: {
		label: "Shipyard",
		desc: "Builds mighty vessels from timber, iron, and the finest components.",
		buildCost: 100000000000,
		slotCostExponent: 1.25,
		prereq: { building: "armoury", product: "cannons" },
		products: {
			hulls: {
				outputKey: "hulls",
				outputAmt: 1,
				inputs: { beams: 3, boards: 2 },
				baseCycleMs: 60000,
				unlockCost: 0,
				baseSlotCost: 22000,
				prereqProduct: null,
				startsUnlocked: true,
			},
			rigging: {
				outputKey: "rigging",
				outputAmt: 1,
				inputs: { shafts: 2, iron_fittings: 2 },
				baseCycleMs: 45000,
				unlockCost: 60000,
				baseSlotCost: 20000,
				prereqProduct: "hulls",
			},
			galleons: {
				outputKey: "galleons",
				outputAmt: 1,
				inputs: { hulls: 1, rigging: 1, cannons: 2 },
				baseCycleMs: 180000,
				unlockCost: 150000,
				baseSlotCost: 45000,
				prereqProduct: "rigging",
			},
			dreadnoughts: {
				outputKey: "dreadnoughts",
				outputAmt: 1,
				inputs: { hulls: 2, rigging: 1, artillery: 2, clockwork: 2 },
				baseCycleMs: 360000,
				unlockCost: 350000,
				baseSlotCost: 90000,
				prereqProduct: "galleons",
			},
		},
	},
} satisfies Record<string, BuildingConfig>;

// Widened view for code that iterates by string key. BUILDING_CONFIG keeps its literal
// types so BuildingKey stays a union of the seven building names.
export const BUILDINGS: Record<string, BuildingConfig> = BUILDING_CONFIG;
